[package]
name = "Unfox"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
serde_repr = "0.1"
npm_rs = "1.0.0"
